#!/bin/bash


if hostname | grep node0 > /dev/null; then
	echo -n
fi

if hostname | grep node1 > /dev/null; then
    # install ettercap, nmap and tshark
    export DEBIAN_FRONTEND=noninteractive
    apt-get update # had libgtk2.0-dev libcurl4-ssl-dev libssl-dev but that is out of date
    DEBIAN_FRONTEND=noninteractive apt-get install debhelper cmake bison flex libltdl3-dev libncurses-dev libncurses5-dev libnet1-dev libpcap-dev libpcre3-dev ghostscript ettercap-text-only tshark arping -y

    # populate /root directory
    tar -xvf /share/education/MITMARPPoisoning_USC/node1-arpspoof.tar -C /root
    cp /share/education/MITMARPPoisoning_USC/.root_profile /root/.bash_profile
fi

if hostname | grep node2 > /dev/null; then
        # install apache2
        DEBIAN_FRONTEND=noninteractive apt-get -y install apache2

	# populate document root directory
	cd /var/www/html
	tar -xvf /share/education/MITMARPPoisoning_USC/node2-arpspoof.tar &> /dev/null
	/bin/chmod 644 /var/www/html/ &> /dev/null
fi

if hostname | grep node3 > /dev/null; then
	# install lynx 
        DEBIAN_FRONTEND=noninteractive apt-get -y install lynx
fi

if hostname | grep node4 > /dev/null; then
        # install apache2
        DEBIAN_FRONTEND=noninteractive apt-get -y install apache2

	# populate document root directory
	cd /var/www/html
	sudo tar -xvf /share/education/MITMARPPoisoning_USC/node4-arpspoof.tar &> /dev/null
	sudo /bin/chmod 644 /var/www/html/* &> /dev/null

        # install vsftpd
        DEBIAN_FRONTEND=noninteractive apt-get -y install vsftpd

fi
