CPATH="/share/education/common"
echo "===> Checking client"
echo "Path $CPATH"
echo "Copying files into posix node."
cd $CPATH; scp -r * posix:/tmp
echo "===> Checking posix"
# echo "Checking installed programs"
# ssh -o stricthostkeychecking=no posix "cd /tmp; /usr/bin/perl check-installed.pl apache2"
# echo "Checking files"
# ssh -o stricthostkeychecking=no posix "cd /tmp; /usr/bin/perl check-files.pl /root/submit.sh /root/restore.sh /etc/mysql/my.cnf"
# echo "Checking processes"
# ssh -o stricthostkeychecking=no posix "cd /tmp; /usr/bin/perl check-processes.pl apache2 mysql"