#!/bin/bash
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install make build-essential flex libnet1-dev libpcap-dev -y
sudo cp -r flooder /usr/local/src
cd /usr/local/src/flooder; sudo make; sudo cp flooder /bin

