#!/bin/bash

sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password zubbazz'
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password zubbazz'

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y lamp-server^
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y vsftpd
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y telnetd
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y bind9

sudo service bind9 start


