#! /bin/sh

WORKDIR=`pwd`
NODES=8
NODECOUNT=1

while [ $NODES -ge $NODECOUNT ]
do
    echo "Stopping node "$NODECOUNT
    ssh node-$NODECOUNT "sudo pkill paws"
    NODECOUNT=`expr $NODECOUNT + 1`    
    sleep 1
done
sudo pkill paws




