#!/bin/bash

# now Debian-only -- 8/22/12 -- pahp

echo "Beginning installation for posix."

DEBUG=1 # set to 1 to DISABLE lockout and share-unmounting for testing

touch /tmp/install.started

ILOG="/var/log/labinstall.log"
KEEPLOG=1 # keep or delete install log at end of install

touch $ILOG
chmod 666 $ILOG

# installer for exploits lab
export LAB="posix"
export BASE="/tmp"
export SOURCE="ExerciseCommon_UCLA"

export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$LAB/$SOURCE" # repos

# support software
export INSTALL="$DOWNLOADS/scripts" 

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi

apt-get update

echo "Installing submission materials..."
cp -rv $THISLAB/root/* /root/ &>> $ILOG
chmod 755 /root/submit.sh &>> $ILOG
chmod 755 /root/restore.sh &>> $ILOG
chmod 755 /root/progcheck.sh &>> $ILOG

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi

apt-get update

echo "Installing submission materials..."
cp -rv $THISLAB/root/* /root/ &>> $ILOG
chmod 755 /root/submit.sh &>> $ILOG
chmod 755 /root/restore.sh &>> $ILOG

# install this stuff on the posix
echo "Installing new /etc/sudoers file..."

# First, create a copy of the sudoers file.
mkdir -p $THISLAB/confs/tmp
cp $THISLAB/confs/sudoers $THISLAB/confs/tmp/ &>> $ILOG

# Second, append the current user to the sudoer's list.
thisuser="$(stat -c '%U' /tmp/posix)"
thisuser+=" ALL=(ALL:ALL) NOPASSWD: ALL"
echo $thisuser >> $THISLAB/confs/tmp/sudoers

# Lastly, copy it to the posix node, then delete the tmp folder.
cp -fv $THISLAB/confs/tmp/sudoers /etc/sudoers &>> $ILOG
chmod 440 /etc/sudoers &>> $ILOG
chmod 755 /root &>> $ILOG
rm -rf $THISLAB/confs/tmp

echo "Success! Creating success stamp."
CreateStamp

echo ">>> Configuration complete for server."
YesLogin

# unmount source files
# rm -rf *

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi
