#!/usr/bin/bash
cp /tmp/snort/Snort/iptablesload /etc/network/if-pre-up.d/
chmod +x /etc/network/if-pre-up.d/iptablesload

apt-get update -y
apt-get install iptables -y
DEBIAN_FRONTEND=noninteractive apt-get install snort -y <<EOF
100.1.10.0/24


EOF

/sbin/iptables -P FORWARD DROP
/sbin/iptables -F FORWARD
/sbin/iptables -A FORWARD -j NFQUEUE
