#!/usr/bin/bash

#####
#  BGP Prefix Hijack Attack
#####
##
# Authors: Vamsi Kambhampati & Dr. Daniel Massey
# Author Org: Colorado State University
# Created On: 10/25/2011
##

# Common installation script for all nodes

# installation needs superuser privilege
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root"
  exit 1
fi

export BASE="."
export CONFS="$BASE/confs"

MYHOST=${HOSTNAME%%.*}

#####

# lockout users from logging in when installation is in progress
#  set to 1 to enable (0 to disable)
LOCKOUT=0

if [ -e $BASE/helper-functions ]; then
  source $BASE/helper-functions
else
  # cannot execute lockout functions if helper routines are not available
  LOCKOUT=0
fi

pushd $BASE

#####

echo
echo ">>> Beginning additional configuration of nodes"
echo

echo "Installing FRR"
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y install frr net-tools
echo "Installing Traceroute"
DEBIAN_FRONTEND=noninteractive apt-get -y install traceroute

echo "Configuring FRR"
if [ -e $BASE/confs/$MYHOST ]; then
  cp -f $BASE/confs/$MYHOST/frr/* /etc/frr/
  echo "Starting FRR..."
  service frr restart
else
  echo "Missing FRR configuration files for $MYHOST"
  echo "  -> Not configuring FRR on $MYHOST"
fi

# machine specific installation steps
#  only executed if a script named "install-$hostname" exists
CUSTOMSCRIPT="$BASE/install-${MYHOST}.sh"
if [ -e $CUSTOMSCRIPT ]; then
    echo ">>> Performing host specific installation tasks for $MYHOST..."
    $CUSTOMSCRIPT >> /tmp/install.log
    echo ">>> Done host specific installation tasks for $MYHOST..."
fi

ip route add 0.0.0.0/0 via 10.6.1.1


echo ">>> Done additional configuration of nodes"

