#!/bin/bash

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y bind9 dnsutils bind9-doc
cp /share/education/DNS_MITM_ColoState/resolv.conf.auth /etc/resolv.conf
cp /share/education/DNS_MITM_ColoState/named.conf.local /etc/bind/named.conf.local
cp /share/education/DNS_MITM_ColoState/named.conf.options.auth /etc/bind/named.conf.options
cp /share/education/DNS_MITM_ColoState/google.com /etc/bind/
cp /share/education/DNS_MITM_ColoState/10 /etc/bind/
/etc/init.d/bind9 restart

