#!/bin/bash

# now Debian-only -- 8/22/12 -- pahp

echo "Beginning installation for server."

DEBUG=1 # set to 1 to DISABLE lockout and share-unmounting for testing

touch /tmp/install.started

ILOG="/var/log/labinstall.log"
KEEPLOG=1 # keep or delete install log at end of install

touch $ILOG
chmod 666 $ILOG

# installer for exploits lab
export LAB="server"
export BASE="/tmp"
export SOURCE="ExerciseCommon_UCLA"

export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$LAB/$SOURCE" # repos

# support software
export INSTALL="$DOWNLOADS/scripts" 

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi


echo ">>> Beginning additional configuration of node for '$LAB' lab." >> $ILOG

apt-get update

# install this stuff on the server

echo "Installing firewall..."
cp -arv $THISLAB/firewall /root/ &>> $ILOG

echo "Installing submission materials..."
cp -rv $THISLAB/root/* /root/ &>> $ILOG
chmod 755 /root/submit.sh &>> $ILOG
chmod 755 /root/restore.sh &>> $ILOG

echo "Installing new /etc/sudoers file..."

# First, create a copy of the sudoers file.
mkdir -p $THISLAB/confs/tmp
cp $THISLAB/confs/sudoers $THISLAB/confs/tmp/ &>> $ILOG

# Second, append the current user to the sudoer's list.
thisuser="$(stat -c '%U' /tmp/server)"
thisuser+=" ALL=(ALL) ALL"
echo $thisuser >> $THISLAB/confs/tmp/sudoers

# Lastly, copy it to the server node, then delete the tmp folder.
cp -fv $THISLAB/confs/tmp/sudoers /etc/sudoers &>> $ILOG
chmod 440 /etc/sudoers &>> $ILOG
chmod 755 -R /root &>> $ILOG
rm -rf $THISLAB/confs/tmp

DEBIAN_FRONTEND=noninteractive apt-get install apache2 iptables nmap net-tools git screen net-tools netcat-openbsd sshpass -y &>> $ILOG
a2enmod ssl &>> $ILOG
a2ensite default-ssl &>> $ILOG
/etc/init.d/apache2 restart &>> $ILOG

DF_TMP=$DEBIAN_FRONTEND # save this var

export DEBIAN_FRONTEND=noninteractive # allow install without password

DEBIAN_FRONTEND=noninteractive apt-get install mariadb-server -y &>> $ILOG
cp -fv $THISLAB/confs/my.cnf /etc/mysql/ &>> $ILOG
/etc/init.d/mariadb restart $>> $ILOG

export DEBIAN_FRONTEND=$DF_TMP # restore default

# set up ssh keys and fix client security hole

# copy key from client to server
mkdir /root/.ssh/
sshpass -p "temppass" scp -o StrictHostKeyChecking=no root@client:/root/.ssh/fwtest /root/.ssh/
chmod -R go-rwx /root/.ssh/

# change root's password on client (using new key) to something better
ssh -o StrictHostKeyChecking=no -i /root/.ssh/fwtest root@client "echo 'root:$(openssl rand -base64 37 | cut -c1-37)' | chpasswd"

echo "Success! Creating success stamp."
CreateStamp

echo ">>> Configuration complete for server."
YesLogin


# unmount source files
rm -rf *

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi

