#!/bin/bash

# this installer is used for both alice and bob; it handles the 
# normal installation stuff, and then calls a custom installer
# for alice or bob. 

# THIS script unmounts UCLAClass -- the custom one can't, because
# when it is running, this process is still in the background!

# installer for mitm lab

ILOG="/var/log/labinstall.log"
echo "Staring victim installer..." &>> $ILOG

# if DEBUG = 1, won't lockout, won't unmount share
# and will KEEP the labinstall logs.
DEBUG=0
KEEPLOG=0

# set up pathnames
export LAB="MITM_UCLA" # name of this lab
export SOURCE="ExerciseCommon_UCLA" # common files

export BASE="/share/education" # source root
export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$SOURCE"

# support software
export INSTALL_UCLA="$DOWNLOADS/scripts"

# load the helper functions
export FUNCTIONS="$INSTALL_UCLA/functions"
source $FUNCTIONS
echo "Loaded helper functions"

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi

# cd into the lab directory
pushd $THISLAB


# post-install function -- advanced configuration feature.
# if 'install-hostname' exists in $THISLAB, we'll run it now.
function HostSpecificInstall {

	MYHOST=${HOSTNAME%%.*}
	CUSTOM="$THISLAB/install-$MYHOST"
	echo "Installing $MYHOST-specific software..."
	if [ -e $CUSTOM ]; then
		$CUSTOM >> $ILOG
	fi
	
	# install crontab to restart services upon a reboot
	sudo cat $THISLAB/confs/crontab-$MYHOST >> /etc/crontab

}


echo
echo ">>> Beginning additional configuration of nodes for '$LAB' lab."
echo 

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install apache2 elinks links wget netcat nmap curl -y &>> $ILOG

# turn off mod_deflate since it makes ettercap's job tougher
sudo a2dismod -f deflate
sudo /etc/init.d/apache2 restart &>> $ILOG

# Students shouldn't be able to log in to alice or bob,
# so we need to modify the passwd file to restrict access.
#$INSTALL_UCLA/userchop.sh

#mv /etc/passwd /etc/passwd.orig
#mv /tmp/passwd /etc/
#chown root:root /etc/passwd
#chmod 644 /etc/passwd
#rm /tmp/passwd

echo "Going to HostSpecificInstall..." &>> $ILOG

HostSpecificInstall

echo "Back from HostSpecificInstall..." &>> $ILOG

echo "Success! Creating success stamp." &>> $ILOG

CreateStamp

echo ">>> Configuration complete." &>> $ILOG

YesLogin


# unmount source files
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	$INSTALL/umountshare &
fi

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi


