#!/bin/bash

# now Debian-only -- 8/22/12 -- pahp

echo "Beginning installation for client."

DEBUG=1 # set to 1 to DISABLE lockout and share-unmounting for testing

touch /tmp/install.started

ILOG="/var/log/labinstall.log"
KEEPLOG=1 # keep or delete install log at end of install

touch $ILOG
chmod 666 $ILOG

# installer for exploits lab
export LAB="client"
export BASE="/tmp"
export SOURCE="ExerciseCommon_UCLA"

export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$LAB/$SOURCE" # repos

# support software
export INSTALL="$DOWNLOADS/scripts" 

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi


echo ">>> Beginning additional configuration of node for '$LAB' lab." >> $ILOG

apt-get update

echo "Installing client"
# install this on the client
DEBIAN_FRONTEND=noninteractive apt-get install nmap elinks links wget curl tcpdump git screen net-tools netcat-openbsd -y &>> $ILOG

# set up ssh keys for fw progress checker

# create /root/.ssh/ if it doesn't exist
mkdir /root/.ssh/ 

# generate the keypair
ssh-keygen -t rsa -N "" -C "fwtest key" -f /root/.ssh/fwtest

# add the public key to authorized_keys
cat /root/.ssh/fwtest.pub >> /root/.ssh/authorized_keys

# fix permissions on /root/.ssh/
chmod -R go-rwx /root/.ssh

# set root ssh password so that the private key can be grabbed by 'server'
echo "root:temppass" | chpasswd

# allow ssh root logins (a bad security practice in general)
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
service ssh restart

echo "Success! Creating success stamp."
CreateStamp

echo ">>> Configuration complete for client."
YesLogin


# unmount source files
rm -rf *

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi

