#!/bin/bash
#
# print a table of ethernet interface names and corresponding IPs, like
#
#               eth1    66.159.240.70
#               eth2    192.168.2.1
#

PATH=$PATH:/sbin

for n in 0 1 2 3 4 5
do
        ETH=$( ifconfig -a | grep -A1 "eth$n" | grep eth | cut -d : -f 1 | gawk '{print $1}' )
        IP=$( ifconfig -a | grep -A1 "eth$n" | grep "inet" | cut -d : -f 2 | gawk '{print $2}' )
        if [ "$IP" ]; then
		if ! echo $IP | grep "^172." > /dev/null; then
                	echo -e "$IP\t$ETH"
		fi
        fi
done
