#!/bin/bash

touch /tmp/install.started

ILOG="/tmp/labinstall.log"
KEEPLOG=1 #keep or delete install log at end of install

touch $ILOG
chmod 666 $ilog

export LAB="UMD_XSS"
export BASE="/share/education"

export THISLAB="$BASE/$LAB"

pushd $THISLAB

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install libcurl3-dev apache2 php5 php5-dev libapache2-mod-php5 php5-cli -y

printf "\n" | pecl install pecl_http-1.7.6.tgz
touch /etc/php5/apache2/conf.d/http.ini
echo "extension=http.so" >> /etc/php5/apache2/conf.d/http.ini
/etc/init.d/apache2 restart

cp /share/education/UMD_XSS/steal.php /var/www/html/
