#!/bin/bash

DEBUG=0 # set to 0 to enable lockout, etc.
KEEPLOG=0 # keep or delete install log

ILOG="/var/log/labinstall.log"
touch $ILOG
chmod 666 $ILOG

echo "Starting 'install'" > $ILOG

# installer for exploits lab
export LAB="sqli"
export BASE="/tmp"
export SOURCE="ExerciseCommon_UCLA"

export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$LAB/$SOURCE" # repos

# support software
export INSTALL="$DOWNLOADS/scripts" 

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi

echo ">>> Beginning additional configuration of node for '$LAB' lab." >> $ILOG

echo "installing software"

####################################
# install the relevant debian packages
####################################

DF_TMP=$DEBIAN_FRONTEND # save this var
export DEBIAN_FRONTEND=noninteractive # allow install without password

# set password for mysql
debconf-set-selections <<< 'mysql-server-5.7 mysql-server/root_password password zubaz99'
debconf-set-selections <<< 'mysql-server-5.7 mysql-server/root_password_again password zubaz99'

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install elinks patch links wget curl tcpdump apache2 apache2-bin mariadb-server mariadb-client php7.4 libapache2-mod-php7.4 php7.4-cli php7.4-mysql tasksel -y
cat -y $THISLAB/confs/apache2.conf >> /etc/apache2/apache2.conf
a2enmod cgid
/etc/init.d/apache2 restart
systemctl restart apache2

export DEBIAN_FRONTEND=$DF_TMP # restore default

####################################
# fccu php script installation
####################################
mkdir -p /var/www/html/fccu
cp $THISLAB/htdocs/index.html /var/www/html
cp -ar $THISLAB/fccu/html/* /var/www/html/fccu/
cp -ar $THISLAB/fccu/cgi/* /usr/lib/cgi-bin/
mysql -uroot -pzubaz99 < $THISLAB/fccu/fccu.sql

/etc/init.d/apache2 restart


####################################
# root level web docs
####################################
if ! cp -ar $THISLAB/htdocs/* /var/www/html
then
	echo "Couldn't install root level docs." >> $ILOG
fi

####################################
# sundry scripts available in /root
####################################
echo "Installing submission materials..."
if ! cp -ar $THISLAB/root /
then
	echo "Couldn't install scripts in /root" >> $ILOG
else
	chmod 755 /root/*.sh
fi


echo "Success! Creating success stamp."
CreateStamp

echo ">>> Configuration complete."
YesLogin


# unmount source files
rm -rf *

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi

