#!/bin/bash

sudo /usr/local/etc/emulab/mkextrafs /mnt/local
if [ ! -d /mnt/local ] ; then
    sudo mkdir /mnt/local
fi
user=`whoami`
sudo chown $user /mnt/local
scp -o stricthostkeychecking=no node-0:/mnt/local/paws_RT.dat /mnt/local


