#!/bin/bash

# now Debian-only -- 8/22/12 -- pahp


DEBUG=0 # set to 1 to DISABLE lockout and share-unmounting for testing
KEEPLOG=0 # keep or delete install log

ILOG="/var/log/labinstall.log"
touch $ILOG
chmod 666 $ILOG

echo "Starting 'install'" > $ILOG

# installer for exploits lab
export LAB="pathname"
export BASE="/tmp"
export SOURCE="ExerciseCommon_UCLA"

export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$LAB/$SOURCE" # repos

# support software
export INSTALL="$DOWNLOADS/scripts" 

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi

echo ">>> Beginning additional configuration of node for '$LAB' lab." >> $ILOG

echo "installing software"

####################################
# build essentials for gcc to be used for mkcwrapper.sh script
####################################
apt-get update
apt-get install build-essential -y
apt-get install gcc -y

####################################
# install the relevant debian packages
####################################

DEBIAN_FRONTEND=noninteractive apt-get install elinks links wget curl tcpdump hexedit -y

DF_TMP=$DEBIAN_FRONTEND # save this var
export DEBIAN_FRONTEND=noninteractive # allow install without password

apt-get install apache2 mariadb-server php libapache2-mod-php php-mysql -y
systemctl restart apache2

# set password for mysql
# debconf-set-selections <<< 'mysql-server-5.1 mysql-server/root_password password verysecurepass'
# debconf-set-selections <<< 'mysql-server-5.1 mysql-server/root_password_again password verysecurepass'

# install apache, php, mysql, and perl
DEBIAN_FRONTEND=noninteractive apt-get install lamp-server^ -y &>> $ILOG
cat $THISLAB/confs/apache2.conf >> /etc/apache2/apache2.conf
a2enmod cgid
/etc/init.d/apache2 restart

# PHP5 is automatically installed and configured.

# export DEBIAN_FRONTEND=$DF_TMP # restore default

####################################
# accounts and memo homedir setup
####################################
# Set up user accounts for Memo

echo "Setting up user accounts..."
# This line is breaking the ssh into the pathname node!
# rm -rf /home/* &>> $ILOG

# setting real passwords (see DevNotes)
useradd wilbar -p '$1$fRqkTieO$w25jISnCEBihVb/s.c.lX0' &>> $ILOG
useradd megaboz -p '$1$9hfkqg8Y$9ISt4JPDqQq.Ik6..rZXo1'
useradd barbazzo -p '$1$UKoOQUPw$vtrmLJpKLSKoV6LTlbJBD1'
useradd gustar -p '$1$YSSC3aFg$l6bRcjnZmmRAQV30Sxe.R/'

cp -r $THISLAB/memo/setup/home/* /home/ &>> $ILOG
cp -r $THISLAB/memo/setup/root/* /root/

pushd /home/
for i in *
do
	  chown $i:$i -R /home/$i
done
popd # leaving home

########################################
# install the CGI programs
########################################

echo "Installing memo.cgi" >> $ILOG

mkdir -p /usr/lib/cgi-bin
pushd /usr/lib/cgi-bin

for f in memo.pl demo.cgi
do
	cp $THISLAB/memo/$f .
	chown root:root $f
	chmod go+rx $f
done

# SUID-root scripts don't work on Apache any more, and suid-perl
# is no longer part of Ubuntu, so we need to use a suid root
# C-wrapper to launch the memo.cgi program SUID root.

# First, mkcwrapper.sh must be runnable for root.
chmod 744 $DOWNLOADS/mkcwrapper.sh
$DOWNLOADS/mkcwrapper.sh /usr/lib/cgi-bin/memo.pl memo.cgi
chown root:root memo.cgi
chmod u+s memo.cgi

popd # leaving /usr/lib/cgi-bin

####################################
# root level web docs
####################################
if ! cp -ar $THISLAB/htdocs/* /var/www/html
then
	echo "Couldn't install root level docs." >> $ILOG
fi

####################################
# sundry scripts available in /root
####################################
echo "Installing submission materials..."
if ! cp -ar $THISLAB/root /
then
	echo "Couldn't install scripts in /root" >> $ILOG
else
	chmod 755 /root/*.sh
fi


echo "Success! Creating success stamp."
CreateStamp

echo ">>> Configuration complete."
YesLogin


# unmount source files
rm -rf *

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi