#!/bin/bash

# now Debian-only -- 8/22/12 -- pahp

DEBUG=1 # set to 1 to DISABLE lockout and share-unmounting for testing

touch /tmp/install.started

ILOG="/var/log/labinstall.log"
KEEPLOG=1 # keep or delete install log at end of install

touch $ILOG
chmod 666 $ILOG

# installer for exploits lab
export LAB="PermissionsFirewalls_UCLA"
export BASE="/share/education"
export SOURCE="ExerciseCommon_UCLA"

export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$SOURCE" # repos

# support software
export INSTALL="$DOWNLOADS/scripts" 

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi


echo ">>> Beginning additional configuration of node for '$LAB' lab." >> $ILOG

apt-get update

if echo $(hostname) | grep client; 
then

        echo "Installing client"
	# install this on the client
	DEBIAN_FRONTEND=noninteractive apt-get install nmap elinks links wget curl tcpdump -y &>> $ILOG

else

	# install this stuff on the server

        echo "Installing firewall..."
	cp -arv $THISLAB/firewall /root/ &>> $ILOG

	echo "Installing submission materials..."
	cp -rv $THISLAB/root/* /root/ &>> $ILOG
	chmod 755 /root/submit.sh &>> $ILOG
	chmod 755 /root/restore.sh &>> $ILOG

	echo "Installing new /etc/sudoers file..."
	cp -fv $THISLAB/confs/sudoers /etc/sudoers &>> $ILOG
	chmod 440 /etc/sudoers &>> $ILOG
	chmod 755 /root &>> $ILOG

	DEBIAN_FRONTEND=noninteractive apt-get install apache2 -y &>> $ILOG
	a2enmod ssl &>> $ILOG
	a2ensite default-ssl &>> $ILOG
	/etc/init.d/apache2 restart &>> $ILOG

	DF_TMP=$DEBIAN_FRONTEND # save this var
	
	export DEBIAN_FRONTEND=noninteractive # allow install without password

	DEBIAN_FRONTEND=noninteractive apt-get install mysql-server -y &>> $ILOG
	cp -fv $THISLAB/confs/my.cnf /etc/mysql/ &>> $ILOG
	/etc/init.d/mysql restart $>> $ILOG

	export DEBIAN_FRONTEND=$DF_TMP # restore default
fi


echo "Success! Creating success stamp."
CreateStamp

echo ">>> Configuration complete."
YesLogin


# unmount source files
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	$INSTALL/umountshare &
fi

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi

